variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  npm_config_cache: $(Pipeline.Workspace)/.npm

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    path: nextjs-graphcms-poc

  - script: vercel --version
    displayName: "Vercel Version"

  # - script: vercel link --token $(VERCEL_SECRET) --confirm
  #   displayName: "Vercel Project Linking"

  # - script: vercel --token $(VERCEL_SECRET) --prod .
  #   condition: and(succeeded(), eq(variables.isMain, 'True'))
  #   displayName: "Deploy to Vercel"

  # - script: vercel --token $(VERCEL_SECRET) . > deployment-url.txt
  #   condition: and(succeeded(), eq(variables.isMain, 'False'))
  #   displayName: "Deploy to Vercel"

  - task: Cache@2
    condition: and(succeeded(), eq(variables.isMain, 'False'))
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)
    displayName: Cache npm

  - script: npm ci
    condition: and(succeeded(), eq(variables.isMain, 'False'))
    displayName: "Install dependencies"

  - task: Cache@2
    condition: and(succeeded(), eq(variables.isMain, 'False'))
    inputs:
      key: 'next | "$(Agent.OS)" | package-lock.json'
      path: "$(System.DefaultWorkingDirectory)/.next/cache"
    displayName: "Cache .next/cache"

  - script: npm run build
    condition: and(succeeded(), eq(variables.isMain, 'False'))
    displayName: "Build the application"
    env:
      PREVIEW_PASSWORD_HASH: $(PREVIEW_PASSWORD_HASH)
      GRAPHCMS_TOKEN: $(GRAPHCMS_TOKEN)
      OKTA_DOMAIN: $(OKTA_DOMAIN)
      OKTA_CLIENT_ID: $(OKTA_CLIENT_ID)
      OKTA_CLIENT_SECRET: $(OKTA_CLIENT_SECRET)

  - script: npm run start:ci
    condition: and(succeeded(), eq(variables.isMain, 'False'))
    displayName: "Start the local server"

  - script: CYPRESS_RECORD_KEY=$(CYPRESS_RECORD_KEY) npm run cy:run-and-record
    condition: and(succeeded(), eq(variables.isMain, 'False'))
    displayName: "Run the Cypress Integration Tests"
    env:
      PREVIEW_EMAIL: $(PREVIEW_EMAIL)
      PREVIEW_PASSWORD: $(PREVIEW_PASSWORD)
      OKTA_DOMAIN: $(OKTA_DOMAIN)
      OKTA_CLIENT_ID: $(OKTA_CLIENT_ID)
