variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    path: nextjs-graphcms-poc

  - script: vercel --version
    displayName: "Vercel Version"

  - script: vercel link --token $(VERCEL_SECRET) --confirm
    displayName: "Vercel Project Linking"

  - script: vercel --token $(VERCEL_SECRET) --prod .
    condition: and(succeeded(), eq(variables.isMain, 'True'))
    displayName: "Deploy to Vercel"

  - script: vercel --token $(VERCEL_SECRET) . > deployment-url.txt
    condition: and(succeeded(), eq(variables.isMain, 'False'))
    displayName: "Deploy to Vercel"

  - script: echo $(cat deployment-url.txt)
    condition: and(succeeded(), eq(variables.isMain, 'False'))
    displayName: "Print the Vercel Preview URL"

  - script: export CYPRESS_BASE_URL=$(cat deployment-url.txt)
    condition: and(succeeded(), eq(variables.isMain, 'False'))
    displayName: "Set the Cypress Base URL to the Vercel Preview URL"

  - script: npm run cy:run-and-record
    condition: and(succeeded(), eq(variables.isMain, 'False'))
    displayName: "Run the Cypress Integration Tests"
